export { Avatar as AvatarDeprecated } from "./deprecated/Avatar/Avatar";
export { AppLink as AppLinkDeprecated, AppLinkTheme } from "./deprecated/AppLink";
export { Button as ButtonDeprecated, ButtonTheme, ButtonSize } from "./deprecated/Button";
export { Dropdown as DropdownDeprecated } from "./deprecated/Popups/Dropdown/Dropdown";
export { Drawer } from "./deprecated/Drawer/Drawer";
export type { DropdownItem } from "./deprecated/Popups/Dropdown/Dropdown";
export { Card as CardDeprecated } from "./deprecated/Card/Card";
export { Code } from "./deprecated/Code/Code";
export { Input as InputDeprecated } from "./deprecated/Input";
export { Modal } from "./deprecated/Modal";
export { Popover as PopoverDeprecated } from "./deprecated/Popups/Popover/Popover";
export { Skeleton as SkeletonDeprecated } from "./deprecated/Skeleton/Skeleton";
export { Select as SelectDeprecated } from "./deprecated/Popups/Select/Select";
export { StarRating } from "./deprecated/StarRating/StarRating";
export { Tabs as TabsDeprecated } from "./deprecated/Tabs/Tabs";
export { Text as TextDeprecated } from "./deprecated/Text";

// redesigned
export { Avatar } from "./redesigned/Avatar/Avatar";
export { AppLink } from "./redesigned/AppLink";
export { AppImage } from "./redesigned/AppImage/AppImage";
export { AppLogo } from "./redesigned/AppLogo/AppLogo";
export { Button } from "./redesigned/Button/Button";
export { ButtonIcon } from "./redesigned/ButtonIcon/ButtonIcon";
export { Card } from "./redesigned/Card/Card";
export { Input } from "./redesigned/Input";
export { Loader } from "./redesigned/Loader";
export { Dropdown } from "./redesigned/Popups/Dropdown/Dropdown";
export { Overlay } from "./redesigned/Overlay/Overlay";
export { Popover } from "./redesigned/Popups/Popover/Popover";
export { Portal } from "./redesigned/Portal";
export { Skeleton } from "./redesigned/Skeleton/Skeleton";
export { Select } from "./redesigned/Popups/Select/Select";
export type { SelectOption } from "./redesigned/Popups/Select/Select";
export { HStack, VStack } from "./redesigned/Stack";
export { Tabs } from "./redesigned/Tabs/Tabs";
export type { TabItem } from "./redesigned/Tabs/Tabs";
export { Text } from "./redesigned/Text";
